spring.application.name=cheatsheet


#   Eureka server
#    server.port=8761
#    eureka.client.register-with-eureka=false
#    eureka.client.fetch-registry=false


#   Eureka client
#    server.port=8080
#    eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#    eureka.client.register-with-eureka=true                 -- should the service register itself with Eureka. default=true
#    eureka.client.fetch-registry=true                       -- fetching registry from Eureka. default=true
#    eureka.instance.lease-renewal-interval-in-seconds       -- how often (in seconds) the service sends heartbeats to Eureka. default=30
#    eureka.instance.lease-expiration-duration-in-seconds    -- time after which the service is removed if no heartbeats are received. default=90
#    eureka.instance.hostname                                -- used for service instance identification. default=auto-detected
#    eureka.server.enable-self-preservation                  -- prevents automatic removal of instances if many services go down at once. default=true
#    eureka.server.eviction-interval-timer-in-ms             -- how often Eureka cleans up stale instances. default=60000 (60s)
#    eureka.server.expected-client-renewal-interval-seconds  -- expected heartbeat interval from services. default=30
#    eureka.instance.prefer-ip-address                       -- if true, registers instances using their IP address instead of hostname. default=false
#    eureka.instance.instance-id                             -- custom identifier for the service instance. default=autogenerated


#   Graceful shutdown using actuator (client)
#    management.endpoints.web.exposure.include=shutdown
#    management.endpoint.shutdown.enabled=true


#   localhost://8761/eureka/apps                             -- XML file with list of all registered services
